
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 30;
  public static final int DISTINTO = 21;
  public static final int CHAR = 46;
  public static final int POR = 9;
  public static final int PUNTOYCOMA = 27;
  public static final int TCHAR = 5;
  public static final int ENTERO = 2;
  public static final int CASE = 39;
  public static final int GRABARRAS = 49;
  public static final int DOUBLE = 45;
  public static final int INT = 44;
  public static final int LLAVE_C = 26;
  public static final int FOR = 37;
  public static final int LLAVE_A = 25;
  public static final int WRITE = 32;
  public static final int NOT = 8;
  public static final int MENORIGUAL = 19;
  public static final int AND = 6;
  public static final int IGUAL = 11;
  public static final int OR = 7;
  public static final int BOOL = 47;
  public static final int MAIN = 43;
  public static final int IF = 33;
  public static final int ID = 3;
  public static final int MAYORIGUAL = 18;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 14;
  public static final int error = 1;
  public static final int MENOS = 13;
  public static final int MENOR = 17;
  public static final int BREAK = 41;
  public static final int VOID = 42;
  public static final int SWITCH = 38;
  public static final int MAYOR = 16;
  public static final int ELSE = 34;
  public static final int PUNTO = 28;
  public static final int PARENTESIS_C = 23;
  public static final int TEXTOENTRECOMILLAS = 24;
  public static final int IGUALIGUAL = 20;
  public static final int WHILE = 35;
  public static final int PARENTESIS_A = 22;
  public static final int DEFAULT = 40;
  public static final int STRING = 48;
  public static final int FALSE = 15;
  public static final int DIVISION = 12;
  public static final int APOSTROFE = 29;
  public static final int DO = 36;
  public static final int CONSOLE = 31;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "ID",
  "DECIMAL",
  "TCHAR",
  "AND",
  "OR",
  "NOT",
  "POR",
  "MAS",
  "IGUAL",
  "DIVISION",
  "MENOS",
  "TRUE",
  "FALSE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "IGUALIGUAL",
  "DISTINTO",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "TEXTOENTRECOMILLAS",
  "LLAVE_A",
  "LLAVE_C",
  "PUNTOYCOMA",
  "PUNTO",
  "APOSTROFE",
  "DOSPUNTOS",
  "CONSOLE",
  "WRITE",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "VOID",
  "MAIN",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOL",
  "STRING",
  "GRABARRAS"
  };
}

