
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 11;
  public static final int AND = 4;
  public static final int PUNTO = 24;
  public static final int IGUALIGUAL = 18;
  public static final int MENOR = 15;
  public static final int PUNTOYCOMA = 23;
  public static final int TEXTOENTRECOMILLAS = 22;
  public static final int MENORIGUAL = 17;
  public static final int OR = 5;
  public static final int IGUAL = 9;
  public static final int DIVISION = 10;
  public static final int NOT = 6;
  public static final int CONSOLE = 26;
  public static final int TRUE = 12;
  public static final int WRITE = 27;
  public static final int ID = 3;
  public static final int POR = 7;
  public static final int MOSTRAR = 25;
  public static final int DISTINTO = 19;
  public static final int MAYOR = 14;
  public static final int EOF = 0;
  public static final int MAYORIGUAL = 16;
  public static final int FALSE = 13;
  public static final int PARENTESIS_C = 21;
  public static final int error = 1;
  public static final int PARENTESIS_A = 20;
  public static final int ENTERO = 2;
  public static final int MAS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "ID",
  "AND",
  "OR",
  "NOT",
  "POR",
  "MAS",
  "IGUAL",
  "DIVISION",
  "MENOS",
  "TRUE",
  "FALSE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "IGUALIGUAL",
  "DISTINTO",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "TEXTOENTRECOMILLAS",
  "PUNTOYCOMA",
  "PUNTO",
  "MOSTRAR",
  "CONSOLE",
  "WRITE"
  };
}

