
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 20;
  public static final int CHAR = 36;
  public static final int POR = 8;
  public static final int PUNTOYCOMA = 26;
  public static final int ENTERO = 2;
  public static final int MOSTRAR = 29;
  public static final int DOUBLE = 35;
  public static final int INT = 34;
  public static final int LLAVE_C = 25;
  public static final int LLAVE_A = 24;
  public static final int WRITE = 31;
  public static final int NOT = 7;
  public static final int MENORIGUAL = 18;
  public static final int AND = 5;
  public static final int IGUAL = 10;
  public static final int OR = 6;
  public static final int BOOL = 37;
  public static final int IF = 32;
  public static final int ID = 3;
  public static final int MAYORIGUAL = 17;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 13;
  public static final int error = 1;
  public static final int MENOS = 12;
  public static final int MENOR = 16;
  public static final int MAYOR = 15;
  public static final int ELSE = 33;
  public static final int PUNTO = 27;
  public static final int PARENTESIS_C = 22;
  public static final int TEXTOENTRECOMILLAS = 23;
  public static final int IGUALIGUAL = 19;
  public static final int PARENTESIS_A = 21;
  public static final int STRING = 38;
  public static final int FALSE = 14;
  public static final int DIVISION = 11;
  public static final int APOSTROFE = 28;
  public static final int CONSOLE = 30;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "ID",
  "DECIMAL",
  "AND",
  "OR",
  "NOT",
  "POR",
  "MAS",
  "IGUAL",
  "DIVISION",
  "MENOS",
  "TRUE",
  "FALSE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "IGUALIGUAL",
  "DISTINTO",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "TEXTOENTRECOMILLAS",
  "LLAVE_A",
  "LLAVE_C",
  "PUNTOYCOMA",
  "PUNTO",
  "APOSTROFE",
  "MOSTRAR",
  "CONSOLE",
  "WRITE",
  "IF",
  "ELSE",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOL",
  "STRING"
  };
}

