
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package jsonn;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 7;
  public static final int TEXTOENTRECOMILLAS = 3;
  public static final int error = 1;
  public static final int DOSPUNTOS = 6;
  public static final int LLAVE_C = 5;
  public static final int DECIMAL = 2;
  public static final int EOF = 0;
  public static final int LLAVE_A = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECIMAL",
  "TEXTOENTRECOMILLAS",
  "LLAVE_A",
  "LLAVE_C",
  "DOSPUNTOS",
  "COMA"
  };
}

